### ISSUE TITLE
Question about read configuration file

### ISSUE THREAD

**Issue by YiweiNiu** [adigenova/fastsg#1]
Hello,

Could you give me some help about the read configuration file?
1. I have several PE and MPE libraries of illumina reads. Should I put one library per line? like this?
```shell
short lib_300 ins_300_R1.fq ins_300_R2.fq 2
short lib_500 ins_500_R1.fq ins_500_R2.fq 2
short lib_3000 ins_3000_R1.fq ins_3000_R2.fq 2
```

2. I also have a PacBio library, but I don't know how to set the insert-sizes. I couldn't find anything helpful about the insert-sizes of PacBio reads by google. And the guy who sent me this data also don't know this.

Thank you in advance!

**Comment by adigenova** [comment]
Hi Yiwei:

The configuration file in your case should be like this:

1.- assuming long reads are error corrected(file are space separated):

short lib_300 ins_300_R1.fq ins_300_R2.fq 2
short lib_500 ins_500_R1.fq ins_500_R2.fq 2
short lib_3000 ins_3000_R1.fq ins_3000_R2.fq 2
long	pac_raw pair_file.fastq.gz 500,1000,2000,3000,4000,5000,6000,7000,10000,12000,15000,20000 2

The K-mer in the previous case for FAST-SG could be something between 20-30, to maximize the short read recall.

If the long read are not error corrected is better to perform two runs of FAST-SG, one for short reads(using a longer k-mer size(k=25 or k=30)) and another for the raw long reads(using a shorter k-mer size(k=19)) 

In the second case you have to create two configuration files:

1.- for short reads:
short lib_300 ins_300_R1.fq ins_300_R2.fq 2
short lib_500 ins_500_R1.fq ins_500_R2.fq 2
short lib_3000 ins_3000_R1.fq ins_3000_R2.fq 2

And then run fast-sg using a  k-mer size of 25 or 30.

2.- for raw long reads :
long	pac_raw pair_file.fastq.gz 500,1000,2000,3000,4000,5000,6000,7000,10000,12000,15000,20000 2

And then run FAST-SG using a  k-mer size of 19 for pacbio.

If you want to use scaffmatch for scaffolding, then  you have to change the ending 2 by 1 in in the configuration files.



Let me know if I can help you more.

Best
Alex


> short lib_300 ins_300_R1.fq ins_300_R2.fq 2

**Comment by YiweiNiu** [comment]
Thank you! Alex. Your reply is very informative. I will try both cases and paste my scaffolding stats here.

**Comment by YiweiNiu** [comment]
Hello Alex, I got several another questions:

1. When I want to use [scaffmatch](http://alan.cs.gsu.edu/NGS/?q=content/scaffmatch) for scaffolding, the configuration of reads shoud be `1` even a paired-end library was used? Is that so?

2. Besides `scaffmatch`, is there any other scaffolding tools I can try? you know, with the results of `fast-sg`. I know some other tools which can also use SAM/BAM as input, such as [BESST](https://github.com/ksahlin/BESST) and [OPERA](https://sourceforge.net/p/operasf/wiki/The%20OPERA%20wiki/). But usually we use `bwa` to generate the SAM/BAM, and I wonder whether the sams generated by `fast-sg` are compatible with these tools. If the answer is yes, is there anything I should tune with the parameters or config file?

3. I noticed that `fast-sg` can run with multiple k-mer at a time, can these SAMs of different k-mers be used together for scaffolding tools like `scaffmatch`, or we can only try one k-mer one time?

Thank you for your time~

**Comment by adigenova** [comment]
Hi Yiwei:

> Le 20 août 2018 à 08:49, Yiwei Niu <notifications@github.com> a écrit :
> 
> Hello Alex, I got several another questions:
> 
> When I want to use scaffmatch for scaffolding, the configuration of reads shoud be 1 even a paired-end library was used? Is that so?
> 
Yes, is just a matter of format, scaffmatch works with reads aligned as single ends, because it does the pairing. However, Fast-SG always map the reads as pairs and this is just a trick to produce a SAM compatible with scaffmatch.
> 
> Besides scaffmatch, is there any other scaffolding tools I can try? you know, with the results of fast-sg. I know some other tools which can also use SAM/BAM as input, such as BESST and OPERA. But usually we use bwa to generate the SAM/BAM, and I wonder whether the sams generated by fast-sg are compatible with these tools. If the answer is yes, is there anything I should tune with the parameters or config file?
> 
Yes, You can use with the same SAMs Opera-LG and BOSS. We tested BESST but it crashed by a division by 0, while computing the contig coverage from synthetic mate pairs.
> 
> I noticed that fast-sg can run with multiple k-mer at a time, can these SAMs of different k-mers be used together for scaffolding tools like scaffmatch, or we can only try one k-mer one time?
> 
If you have long and short reads you can feed the scaffolding tools with differents K-mers. Let says, you mapped your illumina reads using a 25-mers and the long reads with 19-mers, then you can provide both SAM sets to the scaffolder. However if you map for instance the short reads using two k-mers sizes(25 and 30) is better to choose the one Having the best mapping rate.

Examples of the configuration files for the scaffolders are provided in the supplementary text of the Fast-SG manuscript.

Let me know if you have further questions.
Best 
Alex

**Comment by YiweiNiu** [comment]
Got it! Thank you for your quick reply and for your tool~
