### ISSUE TITLE
Using multiple long-read input files, settings for Nanopore data and gzipped FASTQ input

### ISSUE THREAD

**Issue by andreaswallberg** [adigenova/fastsg#4]
Dear developers,

I am testing this tool on a large genome and have Nanopore data in several archives. I have a couple of questions:

- Is it possible to specify more than one sequence input file or should I simply concatenate them? Currently, the program complaints if I provide more than one "ont" line in the aligned file.

- My input reads are 25% between 5-10kbp; 65% 10-20kbp and 10% >20kbp. What insert sizes would you recommend to use?

- I am only using reads with Nanopore QVAL>10 here. Any particular recommendation for kmer sizes?

- When starting the program it reports "MULTI LINE FASTA" as input, although the data format is actually gzipped FASTQ input. Do I need to convert my fastq to fasta or does the program parse the fastq correctly and as expected?

Thanks for your tool and grateful for feedback!

**Comment by adigenova** [comment]
Hi Andreas,

### Is it possible to specify more than one sequence input file or should I simply concatenate them? Currently, the program complaints if I provide more than one "ont" line in the aligned file.

Fast-sg use a configuration file where you can specify each sequence input. An example of the configuration file is available here [configuration](https://github.com/adigenova/fast-sg/blob/master/example/ecoli-reads.txt). Prefix (second column) should be unique for each sequence input.

### My input reads are 25% between 5-10kbp; 65% 10-20kbp and 10% >20kbp. What insert sizes would you recommend to use?

I recommend a spectrum of insert sizes in the range 0.5-40kb.
i.e 500,1000,2000,3000,4000,5000,6000,7000,8000,10000,15000,20000,30000,40000

### I am only using reads with Nanopore QVAL>10 here. Any particular recommendation for kmer sizes?
if read identity is good (>90%), then a k-mer of 40 is recommended. Fast-SG use unique k-mers as anchors to map the long-reads, but the longer the k-mer the lower the number of long-read mapped.   

### When starting the program it reports "MULTI LINE FASTA" as input, although the data format is actually gzipped FASTQ input. Do I need to convert my fastq to fasta or does the program parse the fastq correctly and as expected?
No, Fast-sg employs the kseq library which supports fastq/fasta files compressed. Additionally, sequence qualities are ignored during the mapping stage.
 
Best,

Alex

**Comment by andreaswallberg** [comment]
Hi again!

A quick followup: I have generated different sets of synthetic mate pairs using k-mers of 40, 32 and 24 bp and use Scaffmatch as the downstream tool. Is there any benefit of combining these these sets, for example running scaffmatch with the 40+32 kmer sets at once?

**Comment by adigenova** [comment]
Hi Andreas, 
I have not tested the aggregation of k-mers, but might be redundant. However, if the mapping rate of the 40-mer is much lower than the 32-mer, I think you can win some additional joins by combining them.

 In another thing, I have a working version of Wengan that can handle genomes larger than 4Gb. I did a test on wheat data (16Gb) and worked well. Send me a DM if you want to try it in your genome.

Best,
Alex
